server:
  port: 8090


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyf?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # consumer group-id
      group-id: seconds-kill
    template:
      # 指定 topic id
      default-topic: SECONDS-KILL-TOPIC
    listener:
      # 容器中的线程数，用于提高并发数量
      concurrency: 3

#日志
logging:
  file:
    name: secondkill.log
